# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Geek with an attitude
title_separator: "-"
subtitle: Hello my name is Bud and I'm a geek-a-holic
name: Bud Siddhisena
email: bud@geekaholic.org
description: >- # this means to ignore newlines until "baseurl:"
  Geek and techie, I love tinkering with Linux and FOSS projects. When not 
  geeking out, I'm trading on RH or watching too much Youtube. I also enjoy 
  experimenting with cooking and so far no one has gotten food poisoning!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: geekaholic
github_username:  geekaholic
#google_analytics: <tracking_id>

# Site Author
author:
  name             : "Bud Siddhisena"
  avatar           : "/assets/images/geekaholic-bio.jpg"
  bio              : >-
    Geek and techie, I love tinkering with Linux and FOSS projects. When not 
    geeking out, I'm trading on RH or watching too much Youtube. I also enjoy 
    experimenting with cooking and so far no one has gotten food poisoning!
  location         : "Chicago, IL"
  email            :
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/geekaholic"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/geekaholic"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "http://www.linkedin.com/in/budsiddhisena"
    - label: "Slideshare"
      icon: "fab fa-slideshare"
      url: "http://slideshare.net/geekaholic"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/geekaholic"

# Build settings
#theme: minima
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Social Sharing
twitter:
  username: geekaholic


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
