version: "3"
services:
    app:
        build: .
        command: /bin/bash
        stdin_open: true
        tty: true
        working_dir: /app
        ports:
            - "4000:4000"
        command: /bin/bash
        #command: jekyll serve --host 0.0.0.0
        volumes:
            - .:/app
